name: Update docs
on: 
  workflow_call:
      secrets:
        SSH_GH_PAGES:
          description: 'SSH key for GitHub Pages deployment'
          required: true
jobs:
  update-docs:
    runs-on: ubuntu-latest
    name: Update development docs
    steps:
      - name: Checkout 🛎️ ${{ github.event.repository.name }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout 🛎️ Doc-builder
        uses: actions/checkout@v3
        with:
          repository: unifyai/doc-builder
          path: .doc-builder

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Get cache week key
        id: get-cache-week-key
        run: |
          echo "week-key=$(date +'%Y-%V')" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./.venv
          key: ${{ runner.os }}-pip-${{ steps.get-cache-week-key.outputs.week-key }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create virtual environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv

      - name: Build docs
        run: |
          source .venv/bin/activate
          cd .doc-builder
          ./make_docs_without_docker.sh ..

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: docs/build
          target-folder: "${{ github.event.repository.name }}"
          ssh-key: ${{ secrets.SSH_GH_PAGES }}
          branch: master
          git-config-name: ivy-seed
          git-config-email: ivydl.team@gmail.com
          repository-name: KareemMAX/docs
          clean: true
          # TODO Change it after testing
      
      # TODO add if tagged
      # - name: Get Version
      #   run: |
      #     echo "version_folder=${{ github.ref_name }}/gym" >> $GITHUB_ENV
      
      # - name: Deploy for Multi-Version
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      #   uses: JamesIves/github-pages-deploy-action@v4.4.1
      #   with:
      #     folder: docs/build
      #     target-folder: "${{ env.version_folder }}"
      #     ssh-key: ${{ secrets.SSH_GH_PAGES }}
      #     branch: master
      #     git-config-name: ivy-seed
      #     git-config-email: ivydl.team@gmail.com
      #     repository-name: unifyai/docs
      #     clean: true